### ISSUE TITLE
God danm I was going to make the sync time plugin

### ISSUE THREAD

**Issue by Endermanbugzjfc** [thebigsmileXD/RLSync#1]
### But actually thank you for the web API URL. The one I was using need to be pay or else it will have 1000 times query limit.

**Comment by Endermanbugzjfc** [comment]
Read before closing lol

**Comment by thebigsmileXD** [comment]
@Endermanbugzjfc I won't just close, i will delete. Feel free to open quality pull requests.

**Comment by Endermanbugzjfc** [comment]
wait, issue can be delete?
